### ISSUE TITLE
Couldn't opn a zarr example

### ISSUE THREAD

**Issue by pieper** [InsightSoftwareConsortium/ITKIOOMEZarrNGFF#50]
First off, thanks for doing this awesome work 👍 

But I did run into some trouble trying to load some data that does work when I use the `ome_zarr` package.

There's a gist code that works with the same data source [here](https://gist.github.com/pieper/0e7edcf70c844925ea104e07aedbe92a).

But when I use the `itk.OMEZarrNGFFImageIO` I get this error:

```
>>> zarrEndpoint = "https://uk1s3.embassy.ebi.ac.uk/idr/zarr/v0.1/4007801.zarr"
>>> image = itk.imread(zarrEndpoint, imageio=imageio)
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/opt/sr/python-install/lib/python3.9/site-packages/itk/support/extras.py", line 1314, in imread
    reader = template_reader_type.New(**kwargs)
  File "/opt/sr/python-install/lib/python3.9/site-packages/itk/support/template_class.py", line 661, in New
    return self._NewImageReader(
  File "/opt/sr/python-install/lib/python3.9/site-packages/itk/support/template_class.py", line 165, in _NewImageReader
    imageIO.ReadImageInformation()
RuntimeError: /Users/runner/work/ITKIOOMEZarrNGFF/ITKIOOMEZarrNGFF/src/itkOMEZarrNGFFImageIO.cxx:383:
ITK ERROR: OMEZarrNGFFImageIO(0x7fc84001ae60): tensorstore error: FAILED_PRECONDITION: Error opening "zarr" driver: Error reading https://uk1s3.embassy.ebi.ac.uk/idr/zarr/v0.1/4007801.zarr/0/.zarray: Error parsing object member "fill_value": Expected integer in the range [0, 65535], but received: "0" [source locations='tensorstore-src/tensorstore/internal/json_binding/json_binding.h:859,tensorstore-src/tensorstore/driver/kvs_backed_chunk_driver.cc:1055,tensorstore-src/tensorstore/kvstore/kvstore.cc:252,tensorstore-src/tensorstore/driver/driver.cc:112'] [tensorstore_spec='{\"context\":{\"cache_pool\":{},\"data_copy_concurrency\":{},\"http_request_concurrency\":{},\"http_request_retries\":{}},\"driver\":\"zarr\",\"kvstore\":{\"base_url\":\"https://uk1s3.embassy.ebi.ac.uk\",\"driver\":\"http\",\"path\":\"/idr/zarr/v0.1/4007801.zarr/0/\"},\"recheck_cached_data\":false,\"recheck_cached_metadata\":false}']
```

**Comment by dzenanz** [comment]
This is a deviation from specification, see this issue: https://github.com/google/tensorstore/issues/107.

**Comment by pieper** [comment]
Interesting, thanks.  Funny thing is that this is the reference example dataset that is suggested by the zarr resources I worked from at the time.

In any case do you have other data sources that should be working?  I would like to try loading directly from a bucket, like from s3 or gcs.

**Comment by pieper** [comment]
BTW, I was testing this in Slicer's python, but the same error occurred in a conda based pure python 3.9 environment.  This makes sense if the data doesn't match the spec.

**Comment by tbirdso** [comment]
Hi @pieper , thanks for using ITKIOOMEZarrNGFF 😄 

Yes, as @dzenanz noted, we ran into the same issue in setting up cloud integration tests. We believe it is an underlying issue in Google's Tensorstore library, specifically in that it strictly parses quoted JSON values as strings. As I understand it, this is technically adherent to the JSON spec, but in practice results in brittle parsing that fails on minor deviations in real-world data such as that you linked.

If you are looking for sample data for testing ITKIOOMEZarrNGFF, I suggest referring to OME-Zarr v0.4 data discussed at https://github.com/ome/ome-ngff-prototypes. We have had success in loading this data and currently reference it in our [test suite](https://github.com/InsightSoftwareConsortium/ITKIOOMEZarrNGFF/blob/master/test/itkOMEZarrNGFFHTTPTest.cxx#L52).

If you are looking to load data that is affected by https://github.com/google/tensorstore/issues/107, you may need to download the data yourself and manually edit the OME-Zarr `.zattrs` header file to remove quotes from numeric values, i.e.
```sh
fill_value: 0
```
instead of
```sh
fill_value: "0"
```

Hope that helps.

**Comment by pieper** [comment]
This is great, thanks @tbirdso and @dzenanz !

In case anyone else wants to try in [Slicer](http://slicer.org):
```
pip_install("itk-ioomezarrngff")
import itk
imageio = itk.OMEZarrNGFFImageIO.New()
zarrEndpoint = "https://s3.embl.de/i2k-2020/ngff-example-data/v0.4/zyx.ome.zarr"
image = itk.imread(zarrEndpoint, imageio=imageio)
volumeNode = slicer.util.addVolumeFromArray(image)
slicer.util.setSliceViewerLayers(background=volumeNode, fit=True)
```
gives this:

<img width="1220" alt="image" src="https://github.com/InsightSoftwareConsortium/ITKIOOMEZarrNGFF/assets/126077/fddb58fb-6b91-4551-a4be-1e4c317f86a3">
